#!/usr/bin/python3
"""A module for the square"""


class Square:
    """a square."""
    pass

vi 1-square

#!/usr/bin/python3
"""Square module"""


class Square:
    """Define the square."""

    def __init__(self, size):
        """Constructor.
        Args:
            size: length of square.
        """
        self.__size = size
